### ISSUE TITLE
Use current repeater model for the drill.

### ISSUE THREAD

**Issue by mjstahlberg** [UnvanquishedAssets/res-buildables_src.dpkdir#2]
It looks better and more fitting, and the repeater is not part of the game anymore. The current drill model should be kept somewhere safe, though.

**Comment by illwieckz** [comment]
If deleted the git will keep it in its history, btw, we can just rename the directory and mark the content to be ignored using the `.pakinfo/action/build.txt` file (just writing `ignore path/to/file` lines there).

**Comment by Viech** [comment]
Nah, there is no need to ship it while it's not used.

**Comment by illwieckz** [comment]
#3 merged on this side, see https://github.com/Unvanquished/Unvanquished/pull/1062 on game code side.
